# Generated by Django 2.1.5 on 2019-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='product',
            name='likes_total',
            field=models.IntegerField(default=0),
        ),
    ]
